### ISSUE TITLE
Support for systemd

### ISSUE THREAD

**Issue by issmirnov** [meAmidos/dcind#11]
Hello,

I'm setting up a pipeline in concourse that tests ansible roles. One of my jobs spins up a full (systemd enabled) ubuntu1804 image. However, one of the ansible steps for systemd fails with the following error:

```
Cannot determine cgroup we are running in: No such file or directory
Failed to initialize manager: No such file or director
```

I added the following to my job config:

```
$ source /docker-lib.sh
$ start_docker
$ ls /sys/fs/cgroup
blkio             cpu               cpu,cpuacct       cpuacct           cpuset            devices           freezer           hugetlb           memory            net_cls           net_cls,net_prio  net_prio          perf_event        pids              rdma
```

as we can see, `/sys/fs/cgroup/systemd` does not exist, so it makes sense that the `"/sys/fs/cgroup:/sys/fs/cgroup:ro"` mount from [ansible-role-tester](https://github.com/fubarhouse/ansible-role-tester/blob/d22655684acd0d93822006f8426e4f17725b3b51/util/distributions.go#L54) doesn't pull in systemd support.

I found a suggestion [here](https://github.com/voidlinux/void-packages/issues/9811#issuecomment-381917614) that adds a manual systemd folder creation, and this seems to resolve the issue. My build now works, and systemd is supported.

```
mkdir /sys/fs/cgroup/systemd
mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
```

**My question to @meAmidos is thus: is this the best workaround, and if can we add it to docker-lib.sh**? I'm still learning about cgroups, so I'm not sure what that script does.

**Comment by issmirnov** [comment]
@meAmidos what do you think?

**Comment by meAmidos** [comment]
@issmirnov Thank you for the report and sorry for leaving it unanswered until now.

Apparently, the solution you mentioned is also used in the ["upstream"](https://github.com/concourse/docker-image-resource/blob/master/assets/common.sh) source of `docker-lib.sh`, so I've applied it too. Hopefully, that will resolve the issue.
