### ISSUE TITLE
Docker daemon not started in concourse task (README example broken)

### ISSUE THREAD

**Issue by fenech** [meAmidos/dcind#15]
These two lines were removed from the example in the README:
```bash
source /docker-lib.sh
start_docker
```
But without them, any calls to docker functions cause the following error:
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
Since the `entrypoint.sh` script isn't used when a concourse task is run, these lines need to be in the task script.

**Comment by meAmidos** [comment]
Good catch, thanks.

**Comment by fenech** [comment]
Also, since the `docker-lib.sh` script now has `bash` dependencies (e.g. `declare`), I think that the example should use `bash`, not `sh`.

**Comment by fenech** [comment]
Opened #16
