### ISSUE TITLE
Tag builds on Dockerhub

### ISSUE THREAD

**Issue by sagarjauhari** [meAmidos/dcind#18]
The current build is breaking for me. Please add tags for new releases on dockerhub so I can revert to an older version while the issue is fixed. (I'm using digest to revert to an older cached version for now)

**Comment by gmedders** [comment]
This would be great! Would you be open to tagging semantic versions both in Github for the Dockerfile with corresponding tags in Dockerhub?

**Comment by meAmidos** [comment]
@sagarjauhari Versioning is now enabled. Could you please let me know if `amidos/dcind:1` works for you?

**Comment by meAmidos** [comment]
@gmedders Done. Both repository and images now follow the semver rules.

**Comment by gmedders** [comment]
Awesome, thanks @meAmidos!

**Comment by sagarjauhari** [comment]
Thanks @meAmidos testing the tagged image now

**Comment by sagarjauhari** [comment]
Yes the image with tag `:1` works!
