### ISSUE TITLE
Docker Container does not get attached / Test not visible

### ISSUE THREAD

**Issue by chris-aeviator** [meAmidos/dcind#7]
when running my integration testsuite through either with preconfigured integration test job in my integration.yml file via `docker-compose -f code-repository/integration.yml run tests` or `docker-compose -f code-repository/integration.yml up -d` and directly after `docker-compose -f code-repository/integration.yml run --rm -w /var/www/html/public php php scripts/run-tests.sh --php /usr/local/bin/php --url http://nginx --verbose --color --class DownloadRestrictionsTestcase`  I can see the docker-compose output "starting containers" with their done flags but concourse won't wait for further output and directly proceeds to the next step, in this case `docker-compose -f code-repository/integration.yml down`

**Comment by meAmidos** [comment]
Based on your description, I would assume there is some misconfiguration either in you Docker Compose file or in the container with tests.

I would suggest checking:
- if the tests actually run when executed manually not in a container
- if `docker-compose -f code-repository/integration.yml run tests` runs as expected when called manually

**Comment by chris-aeviator** [comment]
@meAmidos thx for your message - you were right, it was a problem with the integration script itself - will close.
